# SPDX-FileCopyrightText: Copyright (c) Fideus Labs LLC
# SPDX-License-Identifier: MIT
"""RFC-8 "Collections and Extensibility" support (OME-Zarr 0.9.dev3)."""

from .collection import NgffCollection
from .coordinates import (
    coordinate_systems,
    coordinate_transformations,
    set_coordinate_systems,
    set_coordinate_transformations,
)
from .io import (
    from_collection_json,
    from_collection_zarr,
    load_rfc8_node_schema,
    to_collection_json,
    to_collection_zarr,
)
from .labels import (
    LabelAttributes,
    Labels,
    is_label_map,
    labels,
    set_labels,
)
from .model import (
    PATH_TYPE_JSON,
    PATH_TYPE_ZARR,
    RFC8_ID_PATTERN,
    Collection,
    Node,
    OmePath,
    Reference,
    is_collection_node,
    is_prefixed_identifier,
)
from .plate import (
    PlateAttribute,
    PlateEntry,
    WellAttribute,
    acquisition,
    plate,
    plate_collection_from_hcs,
    set_acquisition,
    set_plate,
    set_well,
    well,
)
from .resolve import resolve_location, resolve_ome_document
from .scene import (
    Scene,
    read_scene,
    scene,
    set_scene,
    write_scene,
)
from .serialize import node_from_ome_dict, node_to_ome_dict
from .validation import (
    validate_acquisition_reference_resolves,
    validate_collection,
    validate_coordinate_system_id_required,
    validate_label_color_format,
    validate_label_value_required,
    validate_multiscale_output_consistent,
    validate_node_id_format,
    validate_node_id_unique,
    validate_node_name_required,
    validate_node_name_unique,
    validate_node_nodes_xor_path,
    validate_node_type_required,
    validate_node_version_consistent,
    validate_path_type_known,
    validate_plate_columns_rows_required,
    validate_reference_id_required,
    validate_reference_path_required,
    validate_scene_transformations_required,
    validate_singlescale_transform_shape,
    validate_well_reference_resolves,
)

__all__ = [
    "PATH_TYPE_JSON",
    "PATH_TYPE_ZARR",
    "RFC8_ID_PATTERN",
    "Collection",
    "NgffCollection",
    "Node",
    "OmePath",
    "Reference",
    "from_collection_json",
    "from_collection_zarr",
    "is_collection_node",
    "is_prefixed_identifier",
    "load_rfc8_node_schema",
    "LabelAttributes",
    "Labels",
    "PlateAttribute",
    "PlateEntry",
    "Scene",
    "WellAttribute",
    "acquisition",
    "coordinate_systems",
    "coordinate_transformations",
    "is_label_map",
    "labels",
    "set_labels",
    "node_from_ome_dict",
    "node_to_ome_dict",
    "plate",
    "plate_collection_from_hcs",
    "read_scene",
    "scene",
    "set_scene",
    "write_scene",
    "set_acquisition",
    "set_coordinate_systems",
    "set_coordinate_transformations",
    "set_plate",
    "set_well",
    "resolve_location",
    "resolve_ome_document",
    "to_collection_json",
    "to_collection_zarr",
    "validate_acquisition_reference_resolves",
    "validate_collection",
    "validate_node_id_format",
    "validate_node_id_unique",
    "validate_node_name_required",
    "validate_node_name_unique",
    "validate_node_nodes_xor_path",
    "validate_coordinate_system_id_required",
    "validate_label_color_format",
    "validate_label_value_required",
    "validate_multiscale_output_consistent",
    "validate_node_type_required",
    "validate_node_version_consistent",
    "validate_path_type_known",
    "validate_plate_columns_rows_required",
    "validate_reference_id_required",
    "validate_reference_path_required",
    "validate_scene_transformations_required",
    "validate_singlescale_transform_shape",
    "validate_well_reference_resolves",
    "well",
]
